apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: mchekini/postgres:1
        ports:
        - containerPort: 5432
        env:
        - POSTGRES_PASSWORD: dev